const dashboardTypes = {
    CREATE_GROUP_START : 'CREATE_GROUP_START',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    ADD_USER_START: 'ADD_USER_START',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    GENERATE_LEADS_START: 'GENERATE_LEADS_START',
    GENERATE_LEADS_SUCCESS: 'GENERATE_LEADS_SUCCESS'
}

export default dashboardTypes