const dashboardTypes = {
    SET_CURRENT_GROUP: 'SET_CURRENT_GROUP',
    SET_GROUPS: 'SET_GROUPS',
    CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
    CREATE_GROUP_ERROR : 'CREATE_GROUP_ERROR',
    UPDATE_GROUP_SUCCESS : 'UPDATE_GROUP_SUCCESS',

    SET_CONTACTS: 'SET_CONTACTS',

    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_ERROR: 'ADD_USER_ERROR',
    GENERATE_LEADS_SUCCESS: 'GENERATE_LEADS_SUCCESS',
    GENERATE_LEADS_ERROR: 'GENERATE_LEADS_ERROR',
}

export default dashboardTypes